{% set version = "1.5.1" %}

package:
  name: poetry-plugin-tweak-dependencies-version
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/poetry-plugin-tweak-dependencies-version/poetry_plugin_tweak_dependencies_version-{{ version }}.tar.gz
  sha256: 4e0be2b8e23a04e542c5090deb5b6e191750ec45bace98ea8b55150844c6026b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.9,<3.12
    - poetry ==1.6.*

test:
  imports:
    - poetry_plugin_tweak_dependencies_version
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sbrunner/poetry-plugin-tweak-dependencies-version
  summary: Poetry plugin used to tweak dependency versions
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
