{% set version = "1.5.0" %}

package:
  name: poetry-plugin-tweak-dependencies-version
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/poetry-plugin-tweak-dependencies-version/poetry_plugin_tweak_dependencies_version-{{ version }}.tar.gz
  sha256: 54f30b39ac666b0568c1d54ccc23975824cc79a59c00c6a21ef7374515a60b15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.8,<3.12
    - poetry ==1.5.*

test:
  imports:
    - poetry_plugin_tweak_dependencies_version
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sbrunner/poetry-plugin-tweak-dependencies-version
  summary: Poetry plugin used to tweak dependency versions
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
