{% set version = "1.5.2" %}

package:
  name: poetry-plugin-tweak-dependencies-version
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/py3/p/poetry-plugin-tweak-dependencies-version/poetry_plugin_tweak_dependencies_version-{{ version }}-py3-none-any.whl
  sha256: 1daad5cf7e1e382c29316c512319b7da7264bffa1dd871fa9b9b2547a91f9441

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation poetry_plugin_tweak_dependencies_version-{{ version }}-py3-none-any.whl
    - {{ PYTHON }} -c "__import__('zipfile').ZipFile('poetry_plugin_tweak_dependencies_version-{{ version }}-py3-none-any.whl').extractall()"
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9,<3.12
    - poetry >=1.6,<1.7

test:
  imports:
    - poetry_plugin_tweak_dependencies_version
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sbrunner/poetry-plugin-tweak-dependencies-version
  summary: Poetry plugin used to tweak dependency versions
  license: BSD-2-Clause
  license_file: poetry_plugin_tweak_dependencies_version-{{ version }}.dist-info/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
