# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.5.7"
  name: poetry-plugin-tweak-dependencies-version
  mod: ${{ name | replace("-", "_") }}
  # dulwich not yet available for 3.14
  python_check_max: "3.13"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/py3/p/${{ name }}/${{ mod }}-${{ version }}-py3-none-any.whl
  sha256: c4193e50308da7d75cae3141ad68b03755fef4d4e29d8629a8fdf2cd890069db

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation ${{ mod }}-${{ version }}-py3-none-any.whl
    - ${{ PYTHON }} -c "__import__('zipfile').ZipFile('${{ mod }}-${{ version }}-py3-none-any.whl').extractall()"

requirements:
  host:
    - pip
    - poetry-core
    - python ${{ python_min }}.*
  run:
    - cryptoography
    - idna
    - poetry <2.1.0
    - python >=${{ python_min }}
    - urllib3
    - certifi
    - requests
    - filelock
    - virtualenv

tests:
  - python:
      imports: ${{ mod }}
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*

about:
  summary: Poetry plugin used to tweak dependency versions
  license: BSD-2-Clause
  license_file: ${{ mod }}-${{ version }}.dist-info/LICENSE
  homepage: https://pypi.org/project/poetry-plugin-tweak-dependencies-version
  repository: https://github.com/sbrunner/${{ name }}

extra:
  recipe-maintainers:
    - bollwyvl
